In [15]:
# LSTM

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/NLP/LSTM/WELFake_Dataset.csv")

In [18]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [19]:
# LSTM

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/NLP/LSTM/WELFake_Dataset.csv")

In [22]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [23]:
df.shape

(72134, 4)

In [24]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [25]:
df.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [26]:
df = df.dropna()

In [27]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [28]:
# Independent Variable
X = df.drop(['label'], axis =1)

In [29]:
# Dependent Variable
y = df['label']

In [30]:
X.shape, y.shape

((71537, 3), (71537,))

In [31]:
X.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   
5           5  About Time! Christian Group Sues Amazon and SP...   

                                                text  
0  No comment is expected from Barack Obama Membe...  
2   Now, most of the demonstrators gathered last ...  
3  A dozen politically active pastors came here f...  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...  
5  All we can say on this one is it s about time ...

In [32]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [36]:
import numpy as np
print(np.__version__)

import keras
print(keras.__version__)

2.0.2
3.8.0


In [37]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [38]:
# Vocabulary Size
voc_size = 10000    #It represents the top 10000 most frequent words present in dataset

In [42]:
# OneHot Representation
message = X.copy()
message['title']

0        LAW ENFORCEMENT ON HIGH ALERT Following Threat...
2        UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3        Bobby Jindal, raised Hindu, uses story of Chri...
4        SATAN 2: Russia unvelis an image of its terrif...
5        About Time! Christian Group Sues Amazon and SP...
                               ...                        
72129    Russians steal research on Trump in hack of U....
72130     WATCH: Giuliani Demands That Democrats Apolog...
72131    Migrants Refuse To Leave Train At Refugee Camp...
72132    Trump tussle gives unpopular Mexican leader mu...
72133    Goldman Sachs Endorses Hillary Clinton For Pre...
Name: title, Length: 71537, dtype: object

In [44]:
message = message.reset_index(drop=True)

In [45]:
message['title'][1]

'UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MOST CHARLOTTE RIOTERS WERE “PEACEFUL” PROTESTERS…In Her Home State Of North Carolina [VIDEO]'

In [46]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [47]:
# DataSet Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus=[]

for i in range(0 ,len(message)):
  review = re.sub('[^a-zA-Z]', ' ',message['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [49]:
corpus [1]

'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video'

In [52]:
# One Hot Representation
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr[1]

[7701,
 5930,
 9893,
 4246,
 1372,
 8325,
 2089,
 2637,
 5786,
 647,
 7174,
 6246,
 3660,
 4683]

In [51]:
corpus[1]

'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video'

In [55]:
# Finding the longest Sent
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

lengths = [len(word_tokenize(sent)) for sent in corpus]

max_index = lengths.index(max(lengths))

print(f"Longest sentence: {corpus[max_index]}")
print(f"Length of longest sentence: {lengths[max_index]}")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


Longest sentence: roger stone updat stop steal exit poll program globalist establish creat fals expect close race use fake poll rig vote machin meet expect nationalist constitut free market awaken rothschild soro hillari chanc steal us elect shrink day whole system rig expos american peopl fed elitist deviant panick
Length of longest sentence: 47


In [58]:
# Embedding Representation

sent_length = 50

embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)

print(embedded_docs)

[[   0    0    0 ... 5002 1823 4683]
 [   0    0    0 ... 6246 3660 4683]
 [   0    0    0 ...  151 1648 7507]
 ...
 [   0    0    0 ... 4165 6277 4313]
 [   0    0    0 ...  211 2122 7281]
 [   0    0    0 ... 9832 7380 8139]]


In [59]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0, 7701, 5930, 9893, 4246, 1372, 8325, 2089, 2637,
       5786,  647, 7174, 6246, 3660, 4683], dtype=int32)

In [71]:
# Creating Model
embedding_vector_feature = 100
model = Sequential()
model.add(Embedding(input_dim = voc_size,output_dim = embedding_vector_feature, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

# Build the model by passing data through
model.build(input_shape=(None, sent_length))


In [72]:
print(model.summary())

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 50, 100)        │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 100)            │        80,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,080,501 (4.12 MB)

 Trainable params: 1,080,501 (4.12 MB)

 Non-trainable params: 0 (0.00 B)

None


In [73]:
len(embedded_docs), y.shape

(71537, (71537,))

In [74]:
import numpy as np

In [75]:
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [76]:
X_final.shape , y_final.shape

((71537, 50), (71537,))

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.33, random_state = 42)

In [78]:
# MOdel Training

model.fit(X_train,y_train, validation_data=(X_test, y_test), epochs=10, batch_size = 64)

Epoch 1/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.8312 - loss: 0.3696 - val_accuracy: 0.8994 - val_loss: 0.2395
Epoch 2/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.9264 - loss: 0.1900 - val_accuracy: 0.9046 - val_loss: 0.2305
Epoch 3/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9426 - loss: 0.1452 - val_accuracy: 0.9007 - val_loss: 0.2567
Epoch 4/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9550 - loss: 0.1137 - val_accuracy: 0.8985 - val_loss: 0.2888
Epoch 5/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9646 - loss: 0.0891 - val_accuracy: 0.9002 - val_loss: 0.3150
Epoch 6/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9744 - loss: 0.0681 - val_accuracy: 0.8944 - val_loss: 0.3602
Epoch 7/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.9820 - loss: 0.0496 - val_accuracy: 0.8922 - val_loss: 0.4600
Epoch 8/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.9859 - loss: 0.0400 - val_accurac

In [80]:
y_pred = model.predict(X_test)

738/738 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step


In [85]:
y_pred = np.where(y_pred > 0.5, 1, 0)   #AUC ROC Curve

In [86]:
from sklearn.metrics import accuracy_score

print(f"Accuracy Score: {accuracy_score(y_test,y_pred)}")

Accuracy Score: 0.8954168078617418


In [88]:
from sklearn.metrics import classification_report
print(f"Classification Report : \n{classification_report(y_test, y_pred)}")

Classification Report : 
              precision    recall  f1-score   support

           0       0.89      0.90      0.89     11693
           1       0.90      0.89      0.90     11915

    accuracy                           0.90     23608
   macro avg       0.90      0.90      0.90     23608
weighted avg       0.90      0.90      0.90     23608



In [90]:
from sklearn.metrics import confusion_matrix
print(f"Confusion Matrix : \n{confusion_matrix(y_test, y_pred)}")

Confusion Matrix : 
[[10486  1207]
 [ 1262 10653]]


In [97]:
# Adding the Dropout Layer in the Model Building
from tensorflow.keras.layers import Dropout

embedding_vector_feature = 200
model = Sequential()
model.add(Embedding(input_dim = voc_size, output_dim = embedding_vector_feature))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer ='adam',metrics=['accuracy'])
model.build(input_shape = (None, sent_length))

In [98]:
print(model.summary())

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 50, 200)        │     2,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 50, 200)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 100)            │       120,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,120,501 (8.09 MB)

 Trainable params: 2,120,501 (8.09 MB)

 Non-trainable params: 0 (0.00 B)

None


In [99]:
model.fit(X_train, y_train,validation_data=(X_test, y_test), epochs=10, batch_size = 64)

Epoch 1/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.8297 - loss: 0.3669 - val_accuracy: 0.8999 - val_loss: 0.2333
Epoch 2/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 11s 13ms/step - accuracy: 0.9265 - loss: 0.1854 - val_accuracy: 0.9021 - val_loss: 0.2364
Epoch 3/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9446 - loss: 0.1418 - val_accuracy: 0.9022 - val_loss: 0.2408
Epoch 4/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9557 - loss: 0.1127 - val_accuracy: 0.8973 - val_loss: 0.2857
Epoch 5/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - accuracy: 0.9651 - loss: 0.0879 - val_accuracy: 0.8996 - val_loss: 0.3284
Epoch 6/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9732 - loss: 0.0682 - val_accuracy: 0.8970 - val_loss: 0.3692
Epoch 7/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9790 - loss: 0.0545 - val_accuracy: 0.8962 - val_loss: 0.4014
Epoch 8/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9843 - loss: 0.0429 - val_ac

In [100]:
y_pred = model.predict(X_test)

738/738 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step


In [101]:
y_pred = np.where(y_pred > 0.5, 1,0)

In [102]:
print(f"Accuracy Score : \n{accuracy_score(y_pred, y_test)}")
print(f"Classification Report : \n{classification_report(y_pred, y_test)}")
print(f"Confusion matrix : \n{confusion_matrix(y_pred, y_test)}")

Accuracy Score : 
0.8966028464927144
Classification Report : 
              precision    recall  f1-score   support

           0       0.89      0.90      0.89     11490
           1       0.91      0.89      0.90     12118

    accuracy                           0.90     23608
   macro avg       0.90      0.90      0.90     23608
weighted avg       0.90      0.90      0.90     23608

Confusion matrix : 
[[10371  1119]
 [ 1322 10796]]
